apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-app
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: con1
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 9090
